# Site settings
title: Sass Guidelines
description: "An opinionated styleguide for writing sane, maintainable and scalable Sass"
keywords: CSS, Sass, SCSS, styleguide, guidelines
baseurl: ""
url: "http://sass-guidelin.es"
twitter_username: HugoGiraudel
github_username:  HugoGiraudel

safe: true

# Build settings
exclude: [node_modules]
markdown: kramdown

kramdown:
  auto_ids: true
  toc_levels: 1..2

sass:
  sass_dir: assets/sass
  style: :compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  blanklines: false
  startings: []
