# Site settings
title: Sass Guidelines
description: "An opinionated styleguide for writing sane, maintainable and scalable Sass"
keywords: CSS, Sass, SCSS, styleguide, guidelines
url: "https://sass-guidelin.es"
twitter_username: KittyGiraudel
languages:
  - cz
  - da
  - de
  - el
  - en
  - es
  - fr
  - it
  - ko
  - pl
  - pt
  - ru
  - zh

# Build settings
environment: production
gems:
  - jekyll-sitemap
data_dir: ./_locales
exclude:
  [
    "CHANGELOG.md",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "TRANSLATING.md",
    "assets/images/icons",
    "package.json",
    "package-lock.json",
    "package-scripts.js",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "pages/**/README.md",
    "LICENSE",
    "CNAME",
    "node_modules",
    "vendor",
    "_bin",
    "sw-precache-config.js",
  ]

markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 2..2

sass:
  sass_dir: ./assets/sass
  style: :compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  blanklines: false
  profile: false
  startings: []
